name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "Lean4-AMMs-Fees"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.18.0"