name = "Lean4-AMMs-Fees"
version = "0.1.0"
defaultTargets = ["lean4-amms-fees"]

[[lean_lib]]
name = "AMMLib"

[[lean_lib]]
name = "HelpersLib"
globs = ["HelpersLib.*"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.18.0"

[[lean_exe]]
name = "lean4-amms-fees"
root = "Main"
