name: Deploy Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Lean
        run: |
          curl -O https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          sh elan-init.sh -y
          source $HOME/.elan/env

      - name: Build documentation
        run: |
          cd docbuild
          lake update
          lake build AMMLib:docs HelpersLib:docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docbuild/.lake/build/doc